package detection;

import java.util.List;

import weka.core.Attribute;
import weka.core.FastVector;
import weka.core.Instance;
import weka.core.Instances;

public class WekaDataEyesCombFeat extends WekaData implements WekaFormat {

	private final int numFields = 228;

	public WekaDataEyesCombFeat() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public FastVector createVector() {
		FastVector fvClassVal = new FastVector(2);
		fvClassVal.addElement("1");
		fvClassVal.addElement("0");
		Attribute ClassAttribute = new Attribute("theClass", fvClassVal);
		//Attribute ClassAttribute = new Attribute("theClass");

		FastVector fvBoolVal = new FastVector(2);
		fvBoolVal.addElement("1");
		fvBoolVal.addElement("0");
		
		Attribute Attribute0 = new Attribute("diffArea");
		Attribute Attribute1 = new Attribute("diffX1");
		Attribute Attribute2 = new Attribute("diffX2");
		Attribute Attribute3 = new Attribute("diffY1");
		Attribute Attribute4 = new Attribute("diffY2");
		Attribute Attribute5 = new Attribute("distCenters");
		Attribute Attribute6 = new Attribute("distCorners");
		Attribute Attribute7 = new Attribute("distX");
		Attribute Attribute8 = new Attribute("distY");
		Attribute Attribute9 = new Attribute("isInsideRegion", fvBoolVal);
		
		Attribute Attribute10 = new Attribute("sumHistH_1");
		Attribute Attribute11 = new Attribute("sumHistH_2");
		Attribute Attribute12 = new Attribute("sumHistH_3");
		Attribute Attribute13 = new Attribute("sumHistH_4");
		Attribute Attribute14 = new Attribute("sumHistH_5");
		Attribute Attribute15 = new Attribute("sumHistH_6");
		Attribute Attribute16 = new Attribute("sumHistH_7");
		Attribute Attribute17 = new Attribute("sumHistH_8");
		Attribute Attribute18 = new Attribute("sumHistH_9");
		Attribute Attribute19 = new Attribute("sumHistH_10");
		
		Attribute Attribute20 = new Attribute("sumHistV_1");
		Attribute Attribute21 = new Attribute("sumHistV_2");
		Attribute Attribute22 = new Attribute("sumHistV_3");
		Attribute Attribute23 = new Attribute("sumHistV_4");
		Attribute Attribute24 = new Attribute("sumHistV_5");
		Attribute Attribute25 = new Attribute("sumHistV_6");
		Attribute Attribute26 = new Attribute("sumHistV_7");
		Attribute Attribute27 = new Attribute("sumHistV_8");
		Attribute Attribute28 = new Attribute("sumHistV_9");
		Attribute Attribute29 = new Attribute("sumHistV_10");
		
		Attribute Attribute30 = new Attribute("sumHistR_1");
		Attribute Attribute31 = new Attribute("sumHistR_2");
		Attribute Attribute32 = new Attribute("sumHistR_3");
		Attribute Attribute33 = new Attribute("sumHistR_4");
		Attribute Attribute34 = new Attribute("sumHistR_5");
		Attribute Attribute35 = new Attribute("sumHistR_6");
		Attribute Attribute36 = new Attribute("sumHistR_7");
		Attribute Attribute37 = new Attribute("sumHistR_8");
		Attribute Attribute38 = new Attribute("sumHistR_9");
		Attribute Attribute39 = new Attribute("sumHistR_10");
		Attribute Attribute40 = new Attribute("sumHistR_11");
		Attribute Attribute41 = new Attribute("sumHistR_12");
		Attribute Attribute42 = new Attribute("sumHistR_13");
		Attribute Attribute43 = new Attribute("sumHistR_14");
		Attribute Attribute44 = new Attribute("sumHistR_15");
		Attribute Attribute45 = new Attribute("sumHistR_16");
		Attribute Attribute46 = new Attribute("sumHistR_17");
		Attribute Attribute47 = new Attribute("sumHistR_18");
		Attribute Attribute48 = new Attribute("sumHistR_19");
		Attribute Attribute49 = new Attribute("sumHistR_20");
		Attribute Attribute50 = new Attribute("sumHistR_21");
		Attribute Attribute51 = new Attribute("sumHistR_22");
		Attribute Attribute52 = new Attribute("sumHistR_23");
		Attribute Attribute53 = new Attribute("sumHistR_24");

		Attribute Attribute54 = new Attribute("diffHistH_1");
		Attribute Attribute55 = new Attribute("diffHistH_2");
		Attribute Attribute56 = new Attribute("diffHistH_3");
		Attribute Attribute57 = new Attribute("diffHistH_4");
		Attribute Attribute58 = new Attribute("diffHistH_5");
		Attribute Attribute59 = new Attribute("diffHistH_6");
		Attribute Attribute60 = new Attribute("diffHistH_7");
		Attribute Attribute61 = new Attribute("diffHistH_8");
		Attribute Attribute62 = new Attribute("diffHistH_9");
		Attribute Attribute63 = new Attribute("diffHistH_10");
		
		Attribute Attribute64 = new Attribute("diffHistV_1");
		Attribute Attribute65 = new Attribute("diffHistV_2");
		Attribute Attribute66 = new Attribute("diffHistV_3");
		Attribute Attribute67 = new Attribute("diffHistV_4");
		Attribute Attribute68 = new Attribute("diffHistV_5");
		Attribute Attribute69 = new Attribute("diffHistV_6");
		Attribute Attribute70 = new Attribute("diffHistV_7");
		Attribute Attribute71 = new Attribute("diffHistV_8");
		Attribute Attribute72 = new Attribute("diffHistV_9");
		Attribute Attribute73 = new Attribute("diffHistV_10");
		
		Attribute Attribute74 = new Attribute("diffHistR_1");
		Attribute Attribute75 = new Attribute("diffHistR_2");
		Attribute Attribute76 = new Attribute("diffHistR_3");
		Attribute Attribute77 = new Attribute("diffHistR_4");
		Attribute Attribute78 = new Attribute("diffHistR_5");
		Attribute Attribute79 = new Attribute("diffHistR_6");
		Attribute Attribute80 = new Attribute("diffHistR_7");
		Attribute Attribute81 = new Attribute("diffHistR_8");
		Attribute Attribute82 = new Attribute("diffHistR_9");
		Attribute Attribute83 = new Attribute("diffHistR_10");
		Attribute Attribute84 = new Attribute("diffHistR_11");
		Attribute Attribute85 = new Attribute("diffHistR_12");
		Attribute Attribute86 = new Attribute("diffHistR_13");
		Attribute Attribute87 = new Attribute("diffHistR_14");
		Attribute Attribute88 = new Attribute("diffHistR_15");
		Attribute Attribute89 = new Attribute("diffHistR_16");
		Attribute Attribute90 = new Attribute("diffHistR_17");
		Attribute Attribute91 = new Attribute("diffHistR_18");
		Attribute Attribute92 = new Attribute("diffHistR_19");
		Attribute Attribute93 = new Attribute("diffHistR_20");
		Attribute Attribute94 = new Attribute("diffHistR_21");
		Attribute Attribute95 = new Attribute("diffHistR_22");
		Attribute Attribute96 = new Attribute("diffHistR_23");
		Attribute Attribute97 = new Attribute("diffHistR_24");

		Attribute Attribute98 = new Attribute("edgeMap_1");
		Attribute Attribute99 = new Attribute("edgeMap_2");
		Attribute Attribute100 = new Attribute("edgeMap_3");
		Attribute Attribute101 = new Attribute("edgeMap_4");
		Attribute Attribute102 = new Attribute("edgeMap_5");
		Attribute Attribute103 = new Attribute("edgeMap_6");
		Attribute Attribute104 = new Attribute("edgeMap_7");
		Attribute Attribute105 = new Attribute("edgeMap_8");
		Attribute Attribute106 = new Attribute("edgeMap_9");
		Attribute Attribute107 = new Attribute("edgeMap_10");
		Attribute Attribute108 = new Attribute("edgeMap_11");
		Attribute Attribute109 = new Attribute("edgeMap_12");
		Attribute Attribute110 = new Attribute("edgeMap_13");
		Attribute Attribute111 = new Attribute("edgeMap_14");
		Attribute Attribute112 = new Attribute("edgeMap_15");
		Attribute Attribute113 = new Attribute("edgeMap_16");
		Attribute Attribute114 = new Attribute("edgeMap_17");
		Attribute Attribute115 = new Attribute("edgeMap_18");
		Attribute Attribute116 = new Attribute("edgeMap_19");
		Attribute Attribute117 = new Attribute("edgeMap_20");
		Attribute Attribute118 = new Attribute("edgeMap_21");
		Attribute Attribute119 = new Attribute("edgeMap_22");
		Attribute Attribute120 = new Attribute("edgeMap_23");
		Attribute Attribute121 = new Attribute("edgeMap_24");
		Attribute Attribute122 = new Attribute("edgeMap_25");
		Attribute Attribute123 = new Attribute("edgeMap_26");
		Attribute Attribute124 = new Attribute("edgeMap_27");
		Attribute Attribute125 = new Attribute("edgeMap_28");
		Attribute Attribute126 = new Attribute("edgeMap_29");
		Attribute Attribute127 = new Attribute("edgeMap_30");
		Attribute Attribute128 = new Attribute("edgeMap_31");
		Attribute Attribute129 = new Attribute("edgeMap_32");
		Attribute Attribute130 = new Attribute("edgeMap_33");
		Attribute Attribute131 = new Attribute("edgeMap_34");
		Attribute Attribute132 = new Attribute("edgeMap_35");
		Attribute Attribute133 = new Attribute("edgeMap_36");
		Attribute Attribute134 = new Attribute("edgeMap_37");
		Attribute Attribute135 = new Attribute("edgeMap_38");
		Attribute Attribute136 = new Attribute("edgeMap_39");
		Attribute Attribute137 = new Attribute("edgeMap_40");
		Attribute Attribute138 = new Attribute("edgeMap_41");
		Attribute Attribute139 = new Attribute("edgeMap_42");
		Attribute Attribute140 = new Attribute("edgeMap_43");
		Attribute Attribute141 = new Attribute("edgeMap_44");
		Attribute Attribute142 = new Attribute("edgeMap_45");
		Attribute Attribute143 = new Attribute("edgeMap_46");
		Attribute Attribute144 = new Attribute("edgeMap_47");
		Attribute Attribute145 = new Attribute("edgeMap_48");
		Attribute Attribute146 = new Attribute("edgeMap_49");
		Attribute Attribute147 = new Attribute("edgeMap_50");
		Attribute Attribute148 = new Attribute("edgeMap_51");
		Attribute Attribute149 = new Attribute("edgeMap_52");
		Attribute Attribute150 = new Attribute("edgeMap_53");
		Attribute Attribute151 = new Attribute("edgeMap_54");
		Attribute Attribute152 = new Attribute("edgeMap_55");
		Attribute Attribute153 = new Attribute("edgeMap_56");
		Attribute Attribute154 = new Attribute("edgeMap_57");
		Attribute Attribute155 = new Attribute("edgeMap_58");
		Attribute Attribute156 = new Attribute("edgeMap_59");
		Attribute Attribute157 = new Attribute("edgeMap_60");
		Attribute Attribute158 = new Attribute("edgeMap_61");
		Attribute Attribute159 = new Attribute("edgeMap_62");
		Attribute Attribute160 = new Attribute("edgeMap_63");
		Attribute Attribute161 = new Attribute("edgeMap_64");
		Attribute Attribute162 = new Attribute("edgeMap_65");
		Attribute Attribute163 = new Attribute("edgeMap_66");
		Attribute Attribute164 = new Attribute("edgeMap_67");
		Attribute Attribute165 = new Attribute("edgeMap_68");
		Attribute Attribute166 = new Attribute("edgeMap_69");
		Attribute Attribute167 = new Attribute("edgeMap_70");
		Attribute Attribute168 = new Attribute("edgeMap_71");
		Attribute Attribute169 = new Attribute("edgeMap_72");
		Attribute Attribute170 = new Attribute("edgeMap_73");
		Attribute Attribute171 = new Attribute("edgeMap_74");
		Attribute Attribute172 = new Attribute("edgeMap_75");
		Attribute Attribute173 = new Attribute("edgeMap_76");
		Attribute Attribute174 = new Attribute("edgeMap_77");
		Attribute Attribute175 = new Attribute("edgeMap_78");
		Attribute Attribute176 = new Attribute("edgeMap_79");
		Attribute Attribute177 = new Attribute("edgeMap_80");
		Attribute Attribute178 = new Attribute("edgeMap_81");
		Attribute Attribute179 = new Attribute("edgeMap_82");
		Attribute Attribute180 = new Attribute("edgeMap_83");
		Attribute Attribute181 = new Attribute("edgeMap_84");
		Attribute Attribute182 = new Attribute("edgeMap_85");
		Attribute Attribute183 = new Attribute("edgeMap_86");
		Attribute Attribute184 = new Attribute("edgeMap_87");
		Attribute Attribute185 = new Attribute("edgeMap_88");
		Attribute Attribute186 = new Attribute("edgeMap_89");
		Attribute Attribute187 = new Attribute("edgeMap_90");
		Attribute Attribute188 = new Attribute("edgeMap_91");
		Attribute Attribute189 = new Attribute("edgeMap_92");
		Attribute Attribute190 = new Attribute("edgeMap_93");
		Attribute Attribute191 = new Attribute("edgeMap_94");
		Attribute Attribute192 = new Attribute("edgeMap_95");
		Attribute Attribute193 = new Attribute("edgeMap_96");
		Attribute Attribute194 = new Attribute("edgeMap_97");
		Attribute Attribute195 = new Attribute("edgeMap_98");
		Attribute Attribute196 = new Attribute("edgeMap_99");
		Attribute Attribute197 = new Attribute("edgeMap_100");

		Attribute Attribute198 = new Attribute("diffDistBtwCenters");
		Attribute Attribute199 = new Attribute("diffPercentArea");
		Attribute Attribute200 = new Attribute("diffBpRatio");
		Attribute Attribute201 = new Attribute("avPercentArea");
		Attribute Attribute202 = new Attribute("avBpRatio");
		Attribute Attribute203 = new Attribute("enumEnclosed");
		Attribute Attribute204 = new Attribute("topLeft");
		Attribute Attribute205 = new Attribute("topRight");
		Attribute Attribute206 = new Attribute("bottomLeft");
		Attribute Attribute207 = new Attribute("bottomRight");
		Attribute Attribute208 = new Attribute("left");
		Attribute Attribute209 = new Attribute("right");
		Attribute Attribute210 = new Attribute("top");
		Attribute Attribute211 = new Attribute("bottom");
		Attribute Attribute212 = new Attribute("xOverlap");
		Attribute Attribute213 = new Attribute("yOverlap");
		Attribute Attribute214 = new Attribute("atan0");
		Attribute Attribute215 = new Attribute("atan45");
		Attribute Attribute216 = new Attribute("atan90");
		Attribute Attribute217 = new Attribute("atan135");
		Attribute Attribute218 = new Attribute("atanHistH0");		
		Attribute Attribute219 = new Attribute("atanHistH45");		
		Attribute Attribute220 = new Attribute("atanHistH90");		
		Attribute Attribute221 = new Attribute("atanHistH135");	
		Attribute Attribute222 = new Attribute("atanHistV0");		
		Attribute Attribute223 = new Attribute("atanHistV45");		
		Attribute Attribute224 = new Attribute("atanHistV90");		
		Attribute Attribute225 = new Attribute("atanHistV135");	
		Attribute Attribute226 = new Attribute("area");	

		FastVector fvWekaAttributes = new FastVector(numFields);
		fvWekaAttributes.addElement(Attribute0);    
		fvWekaAttributes.addElement(Attribute1);    
		fvWekaAttributes.addElement(Attribute2);    
		fvWekaAttributes.addElement(Attribute3);    
		fvWekaAttributes.addElement(Attribute4);    
		fvWekaAttributes.addElement(Attribute5); 
		fvWekaAttributes.addElement(Attribute6);    
		fvWekaAttributes.addElement(Attribute7);    
		fvWekaAttributes.addElement(Attribute8);    
		fvWekaAttributes.addElement(Attribute9);    
		fvWekaAttributes.addElement(Attribute10);    
		fvWekaAttributes.addElement(Attribute11);    
		fvWekaAttributes.addElement(Attribute12);    
		fvWekaAttributes.addElement(Attribute13);    
		fvWekaAttributes.addElement(Attribute14);
		fvWekaAttributes.addElement(Attribute15);    
		fvWekaAttributes.addElement(Attribute16);    
		fvWekaAttributes.addElement(Attribute17);    
		fvWekaAttributes.addElement(Attribute18);
		fvWekaAttributes.addElement(Attribute19);    
		fvWekaAttributes.addElement(Attribute20);    
		fvWekaAttributes.addElement(Attribute21);
		fvWekaAttributes.addElement(Attribute22);
		fvWekaAttributes.addElement(Attribute23);
		fvWekaAttributes.addElement(Attribute24);
		fvWekaAttributes.addElement(Attribute25);
		fvWekaAttributes.addElement(Attribute26);
		fvWekaAttributes.addElement(Attribute27);
		fvWekaAttributes.addElement(Attribute28);
		fvWekaAttributes.addElement(Attribute29);
		fvWekaAttributes.addElement(Attribute30);
		fvWekaAttributes.addElement(Attribute31);
		fvWekaAttributes.addElement(Attribute32);
		fvWekaAttributes.addElement(Attribute33);
		fvWekaAttributes.addElement(Attribute34);
		fvWekaAttributes.addElement(Attribute35);
		fvWekaAttributes.addElement(Attribute36);
		fvWekaAttributes.addElement(Attribute37);
		fvWekaAttributes.addElement(Attribute38);
		fvWekaAttributes.addElement(Attribute39);
		fvWekaAttributes.addElement(Attribute40);
		fvWekaAttributes.addElement(Attribute41);
		fvWekaAttributes.addElement(Attribute42);
		fvWekaAttributes.addElement(Attribute43);
		fvWekaAttributes.addElement(Attribute44);
		fvWekaAttributes.addElement(Attribute45);
		fvWekaAttributes.addElement(Attribute46);
		fvWekaAttributes.addElement(Attribute47);
		fvWekaAttributes.addElement(Attribute48);
		fvWekaAttributes.addElement(Attribute49);
		fvWekaAttributes.addElement(Attribute50);
		fvWekaAttributes.addElement(Attribute51);
		fvWekaAttributes.addElement(Attribute52);
		fvWekaAttributes.addElement(Attribute53);
		fvWekaAttributes.addElement(Attribute54);
		fvWekaAttributes.addElement(Attribute55);
		fvWekaAttributes.addElement(Attribute56);
		fvWekaAttributes.addElement(Attribute57);
		fvWekaAttributes.addElement(Attribute58);
		fvWekaAttributes.addElement(Attribute59);
		fvWekaAttributes.addElement(Attribute60);
		fvWekaAttributes.addElement(Attribute61);
		fvWekaAttributes.addElement(Attribute62);
		fvWekaAttributes.addElement(Attribute63);
		fvWekaAttributes.addElement(Attribute64);
		fvWekaAttributes.addElement(Attribute65);
		fvWekaAttributes.addElement(Attribute66);
		fvWekaAttributes.addElement(Attribute67);
		fvWekaAttributes.addElement(Attribute68);
		fvWekaAttributes.addElement(Attribute69);
		fvWekaAttributes.addElement(Attribute70);
		fvWekaAttributes.addElement(Attribute71);
		fvWekaAttributes.addElement(Attribute72);
		fvWekaAttributes.addElement(Attribute73);
		fvWekaAttributes.addElement(Attribute74);
		fvWekaAttributes.addElement(Attribute75);
		fvWekaAttributes.addElement(Attribute76);
		fvWekaAttributes.addElement(Attribute77);
		fvWekaAttributes.addElement(Attribute78);
		fvWekaAttributes.addElement(Attribute79);
		fvWekaAttributes.addElement(Attribute80);
		fvWekaAttributes.addElement(Attribute81);
		fvWekaAttributes.addElement(Attribute82);
		fvWekaAttributes.addElement(Attribute83);
		fvWekaAttributes.addElement(Attribute84);
		fvWekaAttributes.addElement(Attribute85);
		fvWekaAttributes.addElement(Attribute86);
		fvWekaAttributes.addElement(Attribute87);
		fvWekaAttributes.addElement(Attribute88);    
		fvWekaAttributes.addElement(Attribute89);    
		fvWekaAttributes.addElement(Attribute90);    
		fvWekaAttributes.addElement(Attribute91);    
		fvWekaAttributes.addElement(Attribute92);    
		fvWekaAttributes.addElement(Attribute93);    
		fvWekaAttributes.addElement(Attribute94);    
		fvWekaAttributes.addElement(Attribute95);    
		fvWekaAttributes.addElement(Attribute96);    
		fvWekaAttributes.addElement(Attribute97);    
		fvWekaAttributes.addElement(Attribute98);    
		fvWekaAttributes.addElement(Attribute99);    
		fvWekaAttributes.addElement(Attribute100);    
		fvWekaAttributes.addElement(Attribute101);    
		fvWekaAttributes.addElement(Attribute102);    
		fvWekaAttributes.addElement(Attribute103);    
		fvWekaAttributes.addElement(Attribute104);    
		fvWekaAttributes.addElement(Attribute105);    
		fvWekaAttributes.addElement(Attribute106);    
		fvWekaAttributes.addElement(Attribute107);    
		fvWekaAttributes.addElement(Attribute108);    
		fvWekaAttributes.addElement(Attribute109);    
		fvWekaAttributes.addElement(Attribute110);    
		fvWekaAttributes.addElement(Attribute111);    
		fvWekaAttributes.addElement(Attribute112);    
		fvWekaAttributes.addElement(Attribute113);    
		fvWekaAttributes.addElement(Attribute114);    
		fvWekaAttributes.addElement(Attribute115);    
		fvWekaAttributes.addElement(Attribute116);    
		fvWekaAttributes.addElement(Attribute117);    
		fvWekaAttributes.addElement(Attribute118);    
		fvWekaAttributes.addElement(Attribute119);    
		fvWekaAttributes.addElement(Attribute120);    
		fvWekaAttributes.addElement(Attribute121);    
		fvWekaAttributes.addElement(Attribute122);    
		fvWekaAttributes.addElement(Attribute123);    
		fvWekaAttributes.addElement(Attribute124);    
		fvWekaAttributes.addElement(Attribute125);    
		fvWekaAttributes.addElement(Attribute126);    
		fvWekaAttributes.addElement(Attribute127);    
		fvWekaAttributes.addElement(Attribute128);    
		fvWekaAttributes.addElement(Attribute129);    
		fvWekaAttributes.addElement(Attribute130);    
		fvWekaAttributes.addElement(Attribute131);    
		fvWekaAttributes.addElement(Attribute132);    
		fvWekaAttributes.addElement(Attribute133);    
		fvWekaAttributes.addElement(Attribute134);    
		fvWekaAttributes.addElement(Attribute135);    
		fvWekaAttributes.addElement(Attribute136);    
		fvWekaAttributes.addElement(Attribute137);    
		fvWekaAttributes.addElement(Attribute138);    
		fvWekaAttributes.addElement(Attribute139);    
		fvWekaAttributes.addElement(Attribute140);    
		fvWekaAttributes.addElement(Attribute141);    
		fvWekaAttributes.addElement(Attribute142);    
		fvWekaAttributes.addElement(Attribute143);    
		fvWekaAttributes.addElement(Attribute144);    
		fvWekaAttributes.addElement(Attribute145);    
		fvWekaAttributes.addElement(Attribute146);    
		fvWekaAttributes.addElement(Attribute147);    
		fvWekaAttributes.addElement(Attribute148);    
		fvWekaAttributes.addElement(Attribute149);    
		fvWekaAttributes.addElement(Attribute150);    
		fvWekaAttributes.addElement(Attribute151);    
		fvWekaAttributes.addElement(Attribute152);    
		fvWekaAttributes.addElement(Attribute153);    
		fvWekaAttributes.addElement(Attribute154);    
		fvWekaAttributes.addElement(Attribute155);    
		fvWekaAttributes.addElement(Attribute156);    
		fvWekaAttributes.addElement(Attribute157);    
		fvWekaAttributes.addElement(Attribute158);    
		fvWekaAttributes.addElement(Attribute159);    
		fvWekaAttributes.addElement(Attribute160);    
		fvWekaAttributes.addElement(Attribute161);    
		fvWekaAttributes.addElement(Attribute162);    
		fvWekaAttributes.addElement(Attribute163);    
		fvWekaAttributes.addElement(Attribute164);    
		fvWekaAttributes.addElement(Attribute165);    
		fvWekaAttributes.addElement(Attribute166);    
		fvWekaAttributes.addElement(Attribute167);    
		fvWekaAttributes.addElement(Attribute168);    
		fvWekaAttributes.addElement(Attribute169);    
		fvWekaAttributes.addElement(Attribute170);    
		fvWekaAttributes.addElement(Attribute171);    
		fvWekaAttributes.addElement(Attribute172);    
		fvWekaAttributes.addElement(Attribute173);    
		fvWekaAttributes.addElement(Attribute174);    
		fvWekaAttributes.addElement(Attribute175);    
		fvWekaAttributes.addElement(Attribute176);    
		fvWekaAttributes.addElement(Attribute177);    
		fvWekaAttributes.addElement(Attribute178);    
		fvWekaAttributes.addElement(Attribute179);    
		fvWekaAttributes.addElement(Attribute180);    
		fvWekaAttributes.addElement(Attribute181);    
		fvWekaAttributes.addElement(Attribute182);    
		fvWekaAttributes.addElement(Attribute183);    
		fvWekaAttributes.addElement(Attribute184);    
		fvWekaAttributes.addElement(Attribute185);    
		fvWekaAttributes.addElement(Attribute186);    
		fvWekaAttributes.addElement(Attribute187);    
		fvWekaAttributes.addElement(Attribute188);    
		fvWekaAttributes.addElement(Attribute189);    
		fvWekaAttributes.addElement(Attribute190);    
		fvWekaAttributes.addElement(Attribute191);    
		fvWekaAttributes.addElement(Attribute192);    
		fvWekaAttributes.addElement(Attribute193);    
		fvWekaAttributes.addElement(Attribute194);    
		fvWekaAttributes.addElement(Attribute195);    
		fvWekaAttributes.addElement(Attribute196);    
		fvWekaAttributes.addElement(Attribute197);    
		fvWekaAttributes.addElement(Attribute198);    
		fvWekaAttributes.addElement(Attribute199);    
		fvWekaAttributes.addElement(Attribute200);    
		fvWekaAttributes.addElement(Attribute201);    
		fvWekaAttributes.addElement(Attribute202);    
		fvWekaAttributes.addElement(Attribute203);    
		fvWekaAttributes.addElement(Attribute204);    
		fvWekaAttributes.addElement(Attribute205);    
		fvWekaAttributes.addElement(Attribute206);    
		fvWekaAttributes.addElement(Attribute207);    
		fvWekaAttributes.addElement(Attribute208);    
		fvWekaAttributes.addElement(Attribute209);    
		fvWekaAttributes.addElement(Attribute210);    
		fvWekaAttributes.addElement(Attribute211);    
		fvWekaAttributes.addElement(Attribute212);    
		fvWekaAttributes.addElement(Attribute213);    
		fvWekaAttributes.addElement(Attribute214);    
		fvWekaAttributes.addElement(Attribute215);    
		fvWekaAttributes.addElement(Attribute216);    
		fvWekaAttributes.addElement(Attribute217);    
		fvWekaAttributes.addElement(Attribute218);    
		fvWekaAttributes.addElement(Attribute219);    
		fvWekaAttributes.addElement(Attribute220);    
		fvWekaAttributes.addElement(Attribute221);    
		fvWekaAttributes.addElement(Attribute222);    
		fvWekaAttributes.addElement(Attribute223);    
		fvWekaAttributes.addElement(Attribute224);    
		fvWekaAttributes.addElement(Attribute225);    
		fvWekaAttributes.addElement(Attribute226);    
		   
		fvWekaAttributes.addElement(ClassAttribute);

		return fvWekaAttributes;
	}

	@Override
	public Instances createInstances(FastVector fvWekaAttributes,
			List<String> strArray) {
		Instances trainningSet = new Instances("Rel", fvWekaAttributes, numFields);
		String[] tokens;
		for (String str : strArray) {
			//System.out.println(str);
			tokens = str.split(",");
			Instance vector = new Instance(numFields);
			vector.setValue((Attribute)fvWekaAttributes.elementAt(0), Double.parseDouble(tokens[6].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(1), Double.parseDouble(tokens[7].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(2), Double.parseDouble(tokens[8].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(3), Double.parseDouble(tokens[9].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(4), Double.parseDouble(tokens[10].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(5), Double.parseDouble(tokens[11].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(6), Double.parseDouble(tokens[12].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(7), Double.parseDouble(tokens[13].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(8), Double.parseDouble(tokens[14].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(9), tokens[15].trim());
			
			vector.setValue((Attribute)fvWekaAttributes.elementAt(10), Double.parseDouble(tokens[16].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(11), Double.parseDouble(tokens[17].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(12), Double.parseDouble(tokens[18].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(13), Double.parseDouble(tokens[19].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(14), Double.parseDouble(tokens[20].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(15), Double.parseDouble(tokens[21].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(16), Double.parseDouble(tokens[22].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(17), Double.parseDouble(tokens[23].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(18), Double.parseDouble(tokens[24].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(19), Double.parseDouble(tokens[25].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(20), Double.parseDouble(tokens[26].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(21), Double.parseDouble(tokens[27].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(22), Double.parseDouble(tokens[28].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(23), Double.parseDouble(tokens[29].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(24), Double.parseDouble(tokens[30].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(25), Double.parseDouble(tokens[31].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(26), Double.parseDouble(tokens[32].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(27), Double.parseDouble(tokens[33].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(28), Double.parseDouble(tokens[34].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(29), Double.parseDouble(tokens[35].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(30), Double.parseDouble(tokens[36].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(31), Double.parseDouble(tokens[37].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(32), Double.parseDouble(tokens[38].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(33), Double.parseDouble(tokens[39].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(34), Double.parseDouble(tokens[40].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(35), Double.parseDouble(tokens[41].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(36), Double.parseDouble(tokens[42].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(37), Double.parseDouble(tokens[43].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(38), Double.parseDouble(tokens[44].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(39), Double.parseDouble(tokens[45].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(40), Double.parseDouble(tokens[46].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(41), Double.parseDouble(tokens[47].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(42), Double.parseDouble(tokens[48].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(43), Double.parseDouble(tokens[49].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(44), Double.parseDouble(tokens[50].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(45), Double.parseDouble(tokens[51].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(46), Double.parseDouble(tokens[52].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(47), Double.parseDouble(tokens[53].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(48), Double.parseDouble(tokens[54].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(49), Double.parseDouble(tokens[55].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(50), Double.parseDouble(tokens[56].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(51), Double.parseDouble(tokens[57].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(52), Double.parseDouble(tokens[58].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(53), Double.parseDouble(tokens[59].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(54), Double.parseDouble(tokens[60].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(55), Double.parseDouble(tokens[61].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(56), Double.parseDouble(tokens[62].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(57), Double.parseDouble(tokens[63].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(58), Double.parseDouble(tokens[64].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(59), Double.parseDouble(tokens[65].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(60), Double.parseDouble(tokens[66].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(61), Double.parseDouble(tokens[67].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(62), Double.parseDouble(tokens[68].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(63), Double.parseDouble(tokens[69].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(64), Double.parseDouble(tokens[70].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(65), Double.parseDouble(tokens[71].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(66), Double.parseDouble(tokens[72].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(67), Double.parseDouble(tokens[73].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(68), Double.parseDouble(tokens[74].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(69), Double.parseDouble(tokens[75].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(70), Double.parseDouble(tokens[76].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(71), Double.parseDouble(tokens[77].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(72), Double.parseDouble(tokens[78].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(73), Double.parseDouble(tokens[79].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(74), Double.parseDouble(tokens[80].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(75), Double.parseDouble(tokens[81].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(76), Double.parseDouble(tokens[82].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(77), Double.parseDouble(tokens[83].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(78), Double.parseDouble(tokens[84].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(79), Double.parseDouble(tokens[85].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(80), Double.parseDouble(tokens[86].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(81), Double.parseDouble(tokens[87].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(82), Double.parseDouble(tokens[88].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(83), Double.parseDouble(tokens[89].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(84), Double.parseDouble(tokens[90].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(85), Double.parseDouble(tokens[91].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(86), Double.parseDouble(tokens[92].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(87), Double.parseDouble(tokens[93].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(88), Double.parseDouble(tokens[94].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(89), Double.parseDouble(tokens[95].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(90), Double.parseDouble(tokens[96].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(91), Double.parseDouble(tokens[97].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(92), Double.parseDouble(tokens[98].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(93), Double.parseDouble(tokens[99].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(94), Double.parseDouble(tokens[100].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(95), Double.parseDouble(tokens[101].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(96), Double.parseDouble(tokens[102].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(97), Double.parseDouble(tokens[103].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(98), Double.parseDouble(tokens[104].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(99), Double.parseDouble(tokens[105].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(100), Double.parseDouble(tokens[106].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(101), Double.parseDouble(tokens[107].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(102), Double.parseDouble(tokens[108].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(103), Double.parseDouble(tokens[109].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(104), Double.parseDouble(tokens[110].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(105), Double.parseDouble(tokens[111].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(106), Double.parseDouble(tokens[112].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(107), Double.parseDouble(tokens[113].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(108), Double.parseDouble(tokens[114].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(109), Double.parseDouble(tokens[115].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(110), Double.parseDouble(tokens[116].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(111), Double.parseDouble(tokens[117].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(112), Double.parseDouble(tokens[118].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(113), Double.parseDouble(tokens[119].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(114), Double.parseDouble(tokens[120].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(115), Double.parseDouble(tokens[121].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(116), Double.parseDouble(tokens[122].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(117), Double.parseDouble(tokens[123].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(118), Double.parseDouble(tokens[124].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(119), Double.parseDouble(tokens[125].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(120), Double.parseDouble(tokens[126].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(121), Double.parseDouble(tokens[127].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(122), Double.parseDouble(tokens[128].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(123), Double.parseDouble(tokens[129].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(124), Double.parseDouble(tokens[130].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(125), Double.parseDouble(tokens[131].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(126), Double.parseDouble(tokens[132].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(127), Double.parseDouble(tokens[133].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(128), Double.parseDouble(tokens[134].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(129), Double.parseDouble(tokens[135].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(130), Double.parseDouble(tokens[136].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(131), Double.parseDouble(tokens[137].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(132), Double.parseDouble(tokens[138].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(133), Double.parseDouble(tokens[139].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(134), Double.parseDouble(tokens[140].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(135), Double.parseDouble(tokens[141].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(136), Double.parseDouble(tokens[142].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(137), Double.parseDouble(tokens[143].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(138), Double.parseDouble(tokens[144].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(139), Double.parseDouble(tokens[145].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(140), Double.parseDouble(tokens[146].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(141), Double.parseDouble(tokens[147].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(142), Double.parseDouble(tokens[148].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(143), Double.parseDouble(tokens[149].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(144), Double.parseDouble(tokens[150].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(145), Double.parseDouble(tokens[151].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(146), Double.parseDouble(tokens[152].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(147), Double.parseDouble(tokens[153].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(148), Double.parseDouble(tokens[154].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(149), Double.parseDouble(tokens[155].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(150), Double.parseDouble(tokens[156].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(151), Double.parseDouble(tokens[157].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(152), Double.parseDouble(tokens[158].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(153), Double.parseDouble(tokens[159].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(154), Double.parseDouble(tokens[160].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(155), Double.parseDouble(tokens[161].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(156), Double.parseDouble(tokens[162].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(157), Double.parseDouble(tokens[163].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(158), Double.parseDouble(tokens[164].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(159), Double.parseDouble(tokens[165].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(160), Double.parseDouble(tokens[166].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(161), Double.parseDouble(tokens[167].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(162), Double.parseDouble(tokens[168].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(163), Double.parseDouble(tokens[169].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(164), Double.parseDouble(tokens[170].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(165), Double.parseDouble(tokens[171].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(166), Double.parseDouble(tokens[172].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(167), Double.parseDouble(tokens[173].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(168), Double.parseDouble(tokens[174].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(169), Double.parseDouble(tokens[175].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(170), Double.parseDouble(tokens[176].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(171), Double.parseDouble(tokens[177].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(172), Double.parseDouble(tokens[178].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(173), Double.parseDouble(tokens[179].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(174), Double.parseDouble(tokens[180].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(175), Double.parseDouble(tokens[181].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(176), Double.parseDouble(tokens[182].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(177), Double.parseDouble(tokens[183].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(178), Double.parseDouble(tokens[184].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(179), Double.parseDouble(tokens[185].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(180), Double.parseDouble(tokens[186].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(181), Double.parseDouble(tokens[187].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(182), Double.parseDouble(tokens[188].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(183), Double.parseDouble(tokens[189].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(184), Double.parseDouble(tokens[190].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(185), Double.parseDouble(tokens[191].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(186), Double.parseDouble(tokens[192].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(187), Double.parseDouble(tokens[193].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(188), Double.parseDouble(tokens[194].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(189), Double.parseDouble(tokens[195].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(190), Double.parseDouble(tokens[196].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(191), Double.parseDouble(tokens[197].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(192), Double.parseDouble(tokens[198].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(193), Double.parseDouble(tokens[199].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(194), Double.parseDouble(tokens[200].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(195), Double.parseDouble(tokens[201].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(196), Double.parseDouble(tokens[202].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(197), Double.parseDouble(tokens[203].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(198), Double.parseDouble(tokens[204].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(199), Double.parseDouble(tokens[205].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(200), Double.parseDouble(tokens[206].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(201), Double.parseDouble(tokens[207].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(202), Double.parseDouble(tokens[208].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(203), Double.parseDouble(tokens[209].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(204), Double.parseDouble(tokens[210].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(205), Double.parseDouble(tokens[211].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(206), Double.parseDouble(tokens[212].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(207), Double.parseDouble(tokens[213].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(208), Double.parseDouble(tokens[214].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(209), Double.parseDouble(tokens[215].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(210), Double.parseDouble(tokens[216].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(211), Double.parseDouble(tokens[217].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(212), Double.parseDouble(tokens[218].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(213), Double.parseDouble(tokens[219].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(214), Double.parseDouble(tokens[220].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(215), Double.parseDouble(tokens[221].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(216), Double.parseDouble(tokens[222].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(217), Double.parseDouble(tokens[223].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(218), Double.parseDouble(tokens[224].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(219), Double.parseDouble(tokens[225].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(220), Double.parseDouble(tokens[226].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(221), Double.parseDouble(tokens[227].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(222), Double.parseDouble(tokens[228].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(223), Double.parseDouble(tokens[229].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(224), Double.parseDouble(tokens[230].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(225), Double.parseDouble(tokens[231].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(226), Double.parseDouble(tokens[232].trim()));

			//System.out.println(tokens[1].trim());
			vector.setValue((Attribute)fvWekaAttributes.elementAt(227), tokens[1].trim());
			trainningSet.add(vector);
		}
		int cIdx=trainningSet.numAttributes()-1;
		trainningSet.setClassIndex(cIdx);

        return trainningSet;
	}

	@Override
	public void setFields(String str) {
		// TODO Auto-generated method stub
		
	}

}
