package detection;

import java.util.List;

import weka.core.Attribute;
import weka.core.FastVector;
import weka.core.Instance;
import weka.core.Instances;

public class WekaDataEyes extends WekaData implements WekaFormat {
	
	private final int numFields = 137;

	public WekaDataEyes() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public FastVector createVector() {
		FastVector fvClassVal = new FastVector(2);
		fvClassVal.addElement("true");
		fvClassVal.addElement("false");
		Attribute ClassAttribute = new Attribute("theClass", fvClassVal);

		FastVector fvBoolVal = new FastVector(2);
		fvBoolVal.addElement("true");
		fvBoolVal.addElement("false");
		
		Attribute Attribute0 = new Attribute("diffArea");
		Attribute Attribute1 = new Attribute("diffX1");
		Attribute Attribute2 = new Attribute("diffX2");
		Attribute Attribute3 = new Attribute("diffY1");
		Attribute Attribute4 = new Attribute("diffY2");
		Attribute Attribute5 = new Attribute("distCenters");
		Attribute Attribute6 = new Attribute("distCorners");
		Attribute Attribute7 = new Attribute("distX");
		Attribute Attribute8 = new Attribute("distY");
		Attribute Attribute9 = new Attribute("isInsideRegion", fvBoolVal);
		
		Attribute Attribute10 = new Attribute("pixCount_1");
		Attribute Attribute11 = new Attribute("xRange_1");
		Attribute Attribute12 = new Attribute("yRange_1");
		Attribute Attribute13 = new Attribute("isAreaLessThanMax_1");
		Attribute Attribute14 = new Attribute("isAreaMoreThanMin_1");
		Attribute Attribute15 = new Attribute("isXLessThanMax_1");
		Attribute Attribute16 = new Attribute("isYLessThanMax_1");
		Attribute Attribute17 = new Attribute("isRegionEnclosed_1");
		Attribute Attribute18 = new Attribute("isPixCountMoreThanMin_1");
		Attribute Attribute19 = new Attribute("isDistBtwCentersLessThanMax_1");
		Attribute Attribute20 = new Attribute("distBtwCenters_1");
		Attribute Attribute21 = new Attribute("blkPixPercent_1");
		Attribute Attribute22 = new Attribute("sumPix_1");
		Attribute Attribute23 = new Attribute("sdHoriz_1");
		Attribute Attribute24 = new Attribute("sdVert_1");
		Attribute Attribute25 = new Attribute("sdPix_1");
		Attribute Attribute26 = new Attribute("enclosed_1", fvBoolVal);
		Attribute Attribute27 = new Attribute("percentEnclosed_1");
		Attribute Attribute28 = new Attribute("percentArea_1");
		Attribute Attribute29 = new Attribute("histH_1_1");
		Attribute Attribute30 = new Attribute("histH_2_1");
		Attribute Attribute31 = new Attribute("histH_3_1");
		Attribute Attribute32 = new Attribute("histH_4_1");
		Attribute Attribute33 = new Attribute("histH_5_1");
		Attribute Attribute34 = new Attribute("histH_6_1");
		Attribute Attribute35 = new Attribute("histH_7_1");
		Attribute Attribute36 = new Attribute("histH_8_1");
		Attribute Attribute37 = new Attribute("histH_9_1");
		Attribute Attribute38 = new Attribute("histH_10_1");
		Attribute Attribute39 = new Attribute("histV_1_1");
		Attribute Attribute40 = new Attribute("histV_2_1");
		Attribute Attribute41 = new Attribute("histV_3_1");
		Attribute Attribute42 = new Attribute("histV_4_1");
		Attribute Attribute43 = new Attribute("histV_5_1");
		Attribute Attribute44 = new Attribute("histV_6_1");
		Attribute Attribute45 = new Attribute("histV_7_1");
		Attribute Attribute46 = new Attribute("histV_8_1");
		Attribute Attribute47 = new Attribute("histV_9_1");
		Attribute Attribute48 = new Attribute("histV_10_1");
		Attribute Attribute49 = new Attribute("histR_1_1");
		Attribute Attribute50 = new Attribute("histR_2_1");
		Attribute Attribute51 = new Attribute("histR_3_1");
		Attribute Attribute52 = new Attribute("histR_4_1");
		Attribute Attribute53 = new Attribute("histR_5_1");
		Attribute Attribute54 = new Attribute("histR_6_1");
		Attribute Attribute55 = new Attribute("histR_7_1");
		Attribute Attribute56 = new Attribute("histR_8_1");
		Attribute Attribute57 = new Attribute("histR_9_1");
		Attribute Attribute58 = new Attribute("histR_10_1");
		Attribute Attribute59 = new Attribute("histR_11_1");
		Attribute Attribute60 = new Attribute("histR_12_1");
		Attribute Attribute61 = new Attribute("histR_13_1");
		Attribute Attribute62 = new Attribute("histR_14_1");
		Attribute Attribute63 = new Attribute("histR_15_1");
		Attribute Attribute64 = new Attribute("histR_16_1");
		Attribute Attribute65 = new Attribute("histR_17_1");
		Attribute Attribute66 = new Attribute("histR_18_1");
		Attribute Attribute67 = new Attribute("histR_19_1");
		Attribute Attribute68 = new Attribute("histR_20_1");
		Attribute Attribute69 = new Attribute("histR_21_1");
		Attribute Attribute70 = new Attribute("histR_22_1");
		Attribute Attribute71 = new Attribute("histR_23_1");
		Attribute Attribute72 = new Attribute("histR_24_1");

		Attribute Attribute73 = new Attribute("pixCount_2");
		Attribute Attribute74 = new Attribute("xRange_2");
		Attribute Attribute75 = new Attribute("yRange_2");
		Attribute Attribute76 = new Attribute("isAreaLessThanMax_2");
		Attribute Attribute77 = new Attribute("isAreaMoreThanMin_2");
		Attribute Attribute78 = new Attribute("isXLessThanMax_2");
		Attribute Attribute79 = new Attribute("isYLessThanMax_2");
		Attribute Attribute80 = new Attribute("isRegionEnclosed_2");
		Attribute Attribute81 = new Attribute("isPixCountMoreThanMin_2");
		Attribute Attribute82 = new Attribute("isDistBtwCentersLessThanMax_2");
		Attribute Attribute83 = new Attribute("distBtwCenters_2");
		Attribute Attribute84 = new Attribute("blkPixPercent_2");
		Attribute Attribute85 = new Attribute("sumPix_2");
		Attribute Attribute86 = new Attribute("sdHoriz_2");
		Attribute Attribute87 = new Attribute("sdVert_2");
		Attribute Attribute88 = new Attribute("sdPix_2");
		Attribute Attribute89 = new Attribute("enclosed_2", fvBoolVal);
		Attribute Attribute90 = new Attribute("percentEnclosed_2");
		Attribute Attribute91 = new Attribute("percentArea_2");
		Attribute Attribute92 = new Attribute("histH_1_2");
		Attribute Attribute93 = new Attribute("histH_2_2");
		Attribute Attribute94 = new Attribute("histH_3_2");
		Attribute Attribute95 = new Attribute("histH_4_2");
		Attribute Attribute96 = new Attribute("histH_5_2");
		Attribute Attribute97 = new Attribute("histH_6_2");
		Attribute Attribute98 = new Attribute("histH_7_2");
		Attribute Attribute99 = new Attribute("histH_8_2");
		Attribute Attribute100 = new Attribute("histH_9_2");
		Attribute Attribute101 = new Attribute("histH_10_2");
		Attribute Attribute102 = new Attribute("histV_1_2");
		Attribute Attribute103 = new Attribute("histV_2_2");
		Attribute Attribute104 = new Attribute("histV_3_2");
		Attribute Attribute105 = new Attribute("histV_4_2");
		Attribute Attribute106 = new Attribute("histV_5_2");
		Attribute Attribute107 = new Attribute("histV_6_2");
		Attribute Attribute108 = new Attribute("histV_7_2");
		Attribute Attribute109 = new Attribute("histV_8_2");
		Attribute Attribute110 = new Attribute("histV_9_2");
		Attribute Attribute111 = new Attribute("histV_10_2");
		Attribute Attribute112 = new Attribute("histR_1_2");
		Attribute Attribute113 = new Attribute("histR_2_2");
		Attribute Attribute114 = new Attribute("histR_3_2");
		Attribute Attribute115 = new Attribute("histR_4_2");
		Attribute Attribute116 = new Attribute("histR_5_2");
		Attribute Attribute117 = new Attribute("histR_6_2");
		Attribute Attribute118 = new Attribute("histR_7_2");
		Attribute Attribute119 = new Attribute("histR_8_2");
		Attribute Attribute120 = new Attribute("histR_9_2");
		Attribute Attribute121 = new Attribute("histR_10_2");
		Attribute Attribute122 = new Attribute("histR_11_2");
		Attribute Attribute123 = new Attribute("histR_12_2");
		Attribute Attribute124 = new Attribute("histR_13_2");
		Attribute Attribute125 = new Attribute("histR_14_2");
		Attribute Attribute126 = new Attribute("histR_15_2");
		Attribute Attribute127 = new Attribute("histR_16_2");
		Attribute Attribute128 = new Attribute("histR_17_2");
		Attribute Attribute129 = new Attribute("histR_18_2");
		Attribute Attribute130 = new Attribute("histR_19_2");
		Attribute Attribute131 = new Attribute("histR_20_2");
		Attribute Attribute132 = new Attribute("histR_21_2");
		Attribute Attribute133 = new Attribute("histR_22_2");
		Attribute Attribute134 = new Attribute("histR_23_2");
		Attribute Attribute135 = new Attribute("histR_24_2");

		FastVector fvWekaAttributes = new FastVector(137);
		fvWekaAttributes.addElement(Attribute0);    
		fvWekaAttributes.addElement(Attribute1);    
		fvWekaAttributes.addElement(Attribute2);    
		fvWekaAttributes.addElement(Attribute3);    
		fvWekaAttributes.addElement(Attribute4);    
		fvWekaAttributes.addElement(Attribute5); 
		fvWekaAttributes.addElement(Attribute6);    
		fvWekaAttributes.addElement(Attribute7);    
		fvWekaAttributes.addElement(Attribute8);    
		fvWekaAttributes.addElement(Attribute9);    
		fvWekaAttributes.addElement(Attribute10);    
		fvWekaAttributes.addElement(Attribute11);    
		fvWekaAttributes.addElement(Attribute12);    
		fvWekaAttributes.addElement(Attribute13);    
		fvWekaAttributes.addElement(Attribute14);
		fvWekaAttributes.addElement(Attribute15);    
		fvWekaAttributes.addElement(Attribute16);    
		fvWekaAttributes.addElement(Attribute17);    
		fvWekaAttributes.addElement(Attribute18);
		fvWekaAttributes.addElement(Attribute19);    
		fvWekaAttributes.addElement(Attribute20);    
		fvWekaAttributes.addElement(Attribute21);
		fvWekaAttributes.addElement(Attribute22);
		fvWekaAttributes.addElement(Attribute23);
		fvWekaAttributes.addElement(Attribute24);
		fvWekaAttributes.addElement(Attribute25);
		fvWekaAttributes.addElement(Attribute26);
		fvWekaAttributes.addElement(Attribute27);
		fvWekaAttributes.addElement(Attribute28);
		fvWekaAttributes.addElement(Attribute29);
		fvWekaAttributes.addElement(Attribute30);
		fvWekaAttributes.addElement(Attribute31);
		fvWekaAttributes.addElement(Attribute32);
		fvWekaAttributes.addElement(Attribute33);
		fvWekaAttributes.addElement(Attribute34);
		fvWekaAttributes.addElement(Attribute35);
		fvWekaAttributes.addElement(Attribute36);
		fvWekaAttributes.addElement(Attribute37);
		fvWekaAttributes.addElement(Attribute38);
		fvWekaAttributes.addElement(Attribute39);
		fvWekaAttributes.addElement(Attribute40);
		fvWekaAttributes.addElement(Attribute41);
		fvWekaAttributes.addElement(Attribute42);
		fvWekaAttributes.addElement(Attribute43);
		fvWekaAttributes.addElement(Attribute44);
		fvWekaAttributes.addElement(Attribute45);
		fvWekaAttributes.addElement(Attribute46);
		fvWekaAttributes.addElement(Attribute47);
		fvWekaAttributes.addElement(Attribute48);
		fvWekaAttributes.addElement(Attribute49);
		fvWekaAttributes.addElement(Attribute50);
		fvWekaAttributes.addElement(Attribute51);
		fvWekaAttributes.addElement(Attribute52);
		fvWekaAttributes.addElement(Attribute53);
		fvWekaAttributes.addElement(Attribute54);
		fvWekaAttributes.addElement(Attribute55);
		fvWekaAttributes.addElement(Attribute56);
		fvWekaAttributes.addElement(Attribute57);
		fvWekaAttributes.addElement(Attribute58);
		fvWekaAttributes.addElement(Attribute59);
		fvWekaAttributes.addElement(Attribute60);
		fvWekaAttributes.addElement(Attribute61);
		fvWekaAttributes.addElement(Attribute62);
		fvWekaAttributes.addElement(Attribute63);
		fvWekaAttributes.addElement(Attribute64);
		fvWekaAttributes.addElement(Attribute65);
		fvWekaAttributes.addElement(Attribute66);
		fvWekaAttributes.addElement(Attribute67);
		fvWekaAttributes.addElement(Attribute68);
		fvWekaAttributes.addElement(Attribute69);
		fvWekaAttributes.addElement(Attribute70);
		fvWekaAttributes.addElement(Attribute71);
		fvWekaAttributes.addElement(Attribute72);
		fvWekaAttributes.addElement(Attribute73);
		fvWekaAttributes.addElement(Attribute74);
		fvWekaAttributes.addElement(Attribute75);
		fvWekaAttributes.addElement(Attribute76);
		fvWekaAttributes.addElement(Attribute77);
		fvWekaAttributes.addElement(Attribute78);
		fvWekaAttributes.addElement(Attribute79);
		fvWekaAttributes.addElement(Attribute80);
		fvWekaAttributes.addElement(Attribute81);
		fvWekaAttributes.addElement(Attribute82);
		fvWekaAttributes.addElement(Attribute83);
		fvWekaAttributes.addElement(Attribute84);
		fvWekaAttributes.addElement(Attribute85);
		fvWekaAttributes.addElement(Attribute86);
		fvWekaAttributes.addElement(Attribute87);
		fvWekaAttributes.addElement(Attribute88);    
		fvWekaAttributes.addElement(Attribute89);    
		fvWekaAttributes.addElement(Attribute90);    
		fvWekaAttributes.addElement(Attribute91);    
		fvWekaAttributes.addElement(Attribute92);    
		fvWekaAttributes.addElement(Attribute93);    
		fvWekaAttributes.addElement(Attribute94);    
		fvWekaAttributes.addElement(Attribute95);    
		fvWekaAttributes.addElement(Attribute96);    
		fvWekaAttributes.addElement(Attribute97);    
		fvWekaAttributes.addElement(Attribute98);    
		fvWekaAttributes.addElement(Attribute99);    
		fvWekaAttributes.addElement(Attribute100);    
		fvWekaAttributes.addElement(Attribute101);    
		fvWekaAttributes.addElement(Attribute102);    
		fvWekaAttributes.addElement(Attribute103);    
		fvWekaAttributes.addElement(Attribute104);    
		fvWekaAttributes.addElement(Attribute105);    
		fvWekaAttributes.addElement(Attribute106);    
		fvWekaAttributes.addElement(Attribute107);    
		fvWekaAttributes.addElement(Attribute108);    
		fvWekaAttributes.addElement(Attribute109);    
		fvWekaAttributes.addElement(Attribute110);    
		fvWekaAttributes.addElement(Attribute111);    
		fvWekaAttributes.addElement(Attribute112);    
		fvWekaAttributes.addElement(Attribute113);    
		fvWekaAttributes.addElement(Attribute114);
		fvWekaAttributes.addElement(Attribute115);    
		fvWekaAttributes.addElement(Attribute116);    
		fvWekaAttributes.addElement(Attribute117);    
		fvWekaAttributes.addElement(Attribute118);    
		fvWekaAttributes.addElement(Attribute119);    
		fvWekaAttributes.addElement(Attribute120);    
		fvWekaAttributes.addElement(Attribute121);    
		fvWekaAttributes.addElement(Attribute122);    
		fvWekaAttributes.addElement(Attribute123);    
		fvWekaAttributes.addElement(Attribute124);    
		fvWekaAttributes.addElement(Attribute125);    
		fvWekaAttributes.addElement(Attribute126);    
		fvWekaAttributes.addElement(Attribute127);    
		fvWekaAttributes.addElement(Attribute128);    
		fvWekaAttributes.addElement(Attribute129);    
		fvWekaAttributes.addElement(Attribute130);    
		fvWekaAttributes.addElement(Attribute131);    
		fvWekaAttributes.addElement(Attribute132);    
		fvWekaAttributes.addElement(Attribute133);    
		fvWekaAttributes.addElement(Attribute134);    
		fvWekaAttributes.addElement(Attribute135);    
		   
		fvWekaAttributes.addElement(ClassAttribute);

		return fvWekaAttributes;
	}

	@Override
	public Instances createInstances(FastVector fvWekaAttributes,
			List<String> strArray) {
		Instances trainningSet = new Instances("Rel", fvWekaAttributes, 137);
		String[] tokens;
		for (String str : strArray) {
			//System.out.println(str);
			tokens = str.split(",");
			Instance vector = new Instance(137);
			vector.setValue((Attribute)fvWekaAttributes.elementAt(0), Double.parseDouble(tokens[6].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(1), Double.parseDouble(tokens[7].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(2), Double.parseDouble(tokens[8].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(3), Double.parseDouble(tokens[9].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(4), Double.parseDouble(tokens[10].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(5), Double.parseDouble(tokens[11].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(6), Double.parseDouble(tokens[12].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(7), Double.parseDouble(tokens[13].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(8), Double.parseDouble(tokens[14].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(9), tokens[15].trim());
			
			vector.setValue((Attribute)fvWekaAttributes.elementAt(10), Double.parseDouble(tokens[22].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(11), Double.parseDouble(tokens[23].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(12), Double.parseDouble(tokens[24].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(13), Double.parseDouble(tokens[25].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(14), Double.parseDouble(tokens[26].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(15), Double.parseDouble(tokens[27].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(16), Double.parseDouble(tokens[28].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(17), Double.parseDouble(tokens[29].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(18), Double.parseDouble(tokens[30].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(19), Double.parseDouble(tokens[31].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(20), Double.parseDouble(tokens[32].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(21), Double.parseDouble(tokens[33].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(22), Double.parseDouble(tokens[34].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(23), Double.parseDouble(tokens[35].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(24), Double.parseDouble(tokens[36].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(25), Double.parseDouble(tokens[37].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(26), tokens[38].trim());
			vector.setValue((Attribute)fvWekaAttributes.elementAt(27), Double.parseDouble(tokens[39].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(28), Double.parseDouble(tokens[40].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(29), Double.parseDouble(tokens[41].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(30), Double.parseDouble(tokens[42].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(31), Double.parseDouble(tokens[43].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(32), Double.parseDouble(tokens[44].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(33), Double.parseDouble(tokens[45].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(34), Double.parseDouble(tokens[46].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(35), Double.parseDouble(tokens[47].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(36), Double.parseDouble(tokens[48].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(37), Double.parseDouble(tokens[49].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(38), Double.parseDouble(tokens[50].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(39), Double.parseDouble(tokens[51].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(40), Double.parseDouble(tokens[52].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(41), Double.parseDouble(tokens[53].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(42), Double.parseDouble(tokens[54].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(43), Double.parseDouble(tokens[55].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(44), Double.parseDouble(tokens[56].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(45), Double.parseDouble(tokens[57].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(46), Double.parseDouble(tokens[58].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(47), Double.parseDouble(tokens[59].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(48), Double.parseDouble(tokens[60].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(49), Double.parseDouble(tokens[61].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(50), Double.parseDouble(tokens[62].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(51), Double.parseDouble(tokens[63].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(52), Double.parseDouble(tokens[64].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(53), Double.parseDouble(tokens[65].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(54), Double.parseDouble(tokens[66].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(55), Double.parseDouble(tokens[67].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(56), Double.parseDouble(tokens[68].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(57), Double.parseDouble(tokens[69].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(58), Double.parseDouble(tokens[70].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(59), Double.parseDouble(tokens[71].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(60), Double.parseDouble(tokens[72].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(61), Double.parseDouble(tokens[73].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(62), Double.parseDouble(tokens[74].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(63), Double.parseDouble(tokens[75].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(64), Double.parseDouble(tokens[76].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(65), Double.parseDouble(tokens[77].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(66), Double.parseDouble(tokens[78].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(67), Double.parseDouble(tokens[79].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(68), Double.parseDouble(tokens[80].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(69), Double.parseDouble(tokens[81].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(70), Double.parseDouble(tokens[82].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(71), Double.parseDouble(tokens[83].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(72), Double.parseDouble(tokens[84].trim()));
					
			vector.setValue((Attribute)fvWekaAttributes.elementAt(73), Double.parseDouble(tokens[91].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(74), Double.parseDouble(tokens[92].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(75), Double.parseDouble(tokens[93].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(76), Double.parseDouble(tokens[94].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(77), Double.parseDouble(tokens[95].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(78), Double.parseDouble(tokens[96].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(79), Double.parseDouble(tokens[97].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(80), Double.parseDouble(tokens[98].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(81), Double.parseDouble(tokens[99].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(82), Double.parseDouble(tokens[100].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(83), Double.parseDouble(tokens[101].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(84), Double.parseDouble(tokens[102].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(85), Double.parseDouble(tokens[103].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(86), Double.parseDouble(tokens[104].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(87), Double.parseDouble(tokens[105].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(88), Double.parseDouble(tokens[106].trim()));
			
			vector.setValue((Attribute)fvWekaAttributes.elementAt(89), tokens[107].trim());
			
			vector.setValue((Attribute)fvWekaAttributes.elementAt(90), Double.parseDouble(tokens[108].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(91), Double.parseDouble(tokens[109].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(92), Double.parseDouble(tokens[110].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(93), Double.parseDouble(tokens[111].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(94), Double.parseDouble(tokens[112].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(95), Double.parseDouble(tokens[113].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(96), Double.parseDouble(tokens[114].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(97), Double.parseDouble(tokens[115].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(98), Double.parseDouble(tokens[116].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(99), Double.parseDouble(tokens[117].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(100), Double.parseDouble(tokens[118].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(101), Double.parseDouble(tokens[119].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(102), Double.parseDouble(tokens[120].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(103), Double.parseDouble(tokens[121].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(104), Double.parseDouble(tokens[122].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(105), Double.parseDouble(tokens[123].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(106), Double.parseDouble(tokens[124].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(107), Double.parseDouble(tokens[125].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(108), Double.parseDouble(tokens[126].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(109), Double.parseDouble(tokens[127].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(110), Double.parseDouble(tokens[128].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(111), Double.parseDouble(tokens[129].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(112), Double.parseDouble(tokens[130].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(113), Double.parseDouble(tokens[131].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(114), Double.parseDouble(tokens[132].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(115), Double.parseDouble(tokens[133].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(116), Double.parseDouble(tokens[134].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(117), Double.parseDouble(tokens[135].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(118), Double.parseDouble(tokens[136].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(119), Double.parseDouble(tokens[137].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(120), Double.parseDouble(tokens[138].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(121), Double.parseDouble(tokens[139].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(122), Double.parseDouble(tokens[140].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(123), Double.parseDouble(tokens[141].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(124), Double.parseDouble(tokens[142].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(125), Double.parseDouble(tokens[143].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(126), Double.parseDouble(tokens[144].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(127), Double.parseDouble(tokens[145].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(128), Double.parseDouble(tokens[146].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(129), Double.parseDouble(tokens[147].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(130), Double.parseDouble(tokens[148].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(131), Double.parseDouble(tokens[149].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(132), Double.parseDouble(tokens[150].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(133), Double.parseDouble(tokens[151].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(134), Double.parseDouble(tokens[152].trim()));
			vector.setValue((Attribute)fvWekaAttributes.elementAt(135), Double.parseDouble(tokens[153].trim()));

			//System.out.println(tokens[1].trim());
			vector.setValue((Attribute)fvWekaAttributes.elementAt(136), tokens[1].trim());
			trainningSet.add(vector);
		}
		int cIdx=trainningSet.numAttributes()-1;
		trainningSet.setClassIndex(cIdx);

        return trainningSet;
	}

	@Override
	public void setFields(String str) {
		// TODO Auto-generated method stub
		
	}

}
